### ISSUE TITLE
아 우웩 너무 구려요

### ISSUE THREAD

**Issue by dfdddfd** [minibox724/discordpy-EZMusic#1]
너무 구려요
Lavalink를 활용한 음악봇 오픈소스는 없나요?

**Comment by minibox724** [comment]
예시에서 조금 바꾼점밖에 없어서 많이 구립니다.
나중에 시간이 난다면 라바링크 버전으로 바꿔보겠습니다. 지금 미니봇에 라바링크를 이용한 음악봇 소스가 있으니까 참고해보세요
